version: "3.9"
services:
  postgres:
    container_name: postgres
    image: "postgres:16.4"
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:ro
    env_file:
      - ./database.dev.env
    ports:
      - "5432:5432"
    networks:
      - backend
networks:
  backend:
    name: backend
    driver: bridge